version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    volumes:
    - ${POSTGRES_VOLUME:-postgres-volume}:/var/lib/postgresql/data:Z
    environment:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
  pwbportal:
    image: zentekmx/pwbportal:1.3.1
    command: bash -c "/sbin/wait-for-it postgres:5432 -t 60 -- echo 'Database is up' && rails pwb:install:migrations && rails db:create && rails db:migrate && rails pwb:db:seed && rails pwb:db:seed_pages && rails server"
    ports:
    - 3000:3000
    environment:
    - DATABASE_HOST=postgres
    - DB_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
    - DB_ADMIN_USERNAME=${POSTGRES_USER}
    - DATABASE_NAME=${POSTGRES_DB}
    depends_on:
    - postgres

volumes:
    postgres-volume:
